# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#                      Input Configuration                      ┃
# ┃                      输入设备配置                            ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki | 输入文档：https://wiki.hyprland.org/Configuring/Variables/#input

input {
    # Follow mouse cursor focus behavior | 鼠标焦点跟随行为：0=off, 1=simple, 2=smart, 3=force
    follow_mouse = 2

    # Override focus when switching to floating windows | 切换到浮动窗口时覆盖焦点
    float_switch_override_focus = 2
}
